name: Bug report
description: Report a defect or unintended behavior.
title: "[Bug] "
labels: ["type:bug", "status:needs-triage", "p1"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: Clear, short description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide minimal steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, versions, model names, etc.
      placeholder: |
        OS:
        App version / commit:
        Ollama model:
        Embedding model:
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste logs or add screenshots (redact sensitive data).
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "p0"
        - "p1"
        - "p2"
        - "p3"
    validations:
      required: true